remotes::install_github("mrc-ide/malariasimulation@e51c6bcc66be768b4e80985768f8c404538f0b84")
remotes::install_github("mrc-ide/site@site2")
remotes::install_github("mrc-ide/cali@cali2")
remotes::install_github("mrc-ide/postie@postie2")
remotes::install_github("mrc-ide/scene@scene2")
remotes::install_github("mrc-ide/peeps")
install.packages(
  "orderly2",
  repos = c("https://mrc-ide.r-universe.dev", "https://cloud.r-project.org")
)
install.packages("sf")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("quarto")